name: Publish Development Branch
on: workflow_dispatch
jobs:
    build-site:
        runs-on: ubuntu-latest
        env:
            NODE_ENV: production
        steps:
            - name: Checkout 'main' branch
              uses: actions/checkout@v4

            - name: Setup Node caching
              uses: actions/setup-node@v4
              with:
                node-version: 22
                cache: 'npm'

            - name: Pull dependencies
              run: npm ci

            - name: Build page
              run: npm run build

            - name: Checkout 'dev' branch
              uses: actions/checkout@v4
              with:
                ref: dev
                path: dev

            - name: Modify 'dev' build to output under experimental
              run: cd dev && sed 's|choreographer/|choreographer/experimental/|' -i vite.config.ts && cd ../

            - name: Build 'dev' branch
              run: cd dev && npm ci && npm run build && cd ../

            - name: Copy 'dev' branch output to main page
              run: mv dev/dist dist/experimental

            - name: Upload built page as artifact
              uses: actions/upload-pages-artifact@v3
              with:
                path: dist/

    publish-site:
        permissions:
            pages: write
            id-token: write

        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}

        runs-on: ubuntu-latest
        needs: build-site
        steps:
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4